# Generated by Django 3.2 on 2021-05-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='summary',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
