# Generated by Django 3.2 on 2021-05-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='descritption',
            new_name='description',
        ),
    ]
