# Generated by Django 3.2 on 2021-05-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_descritption_cart_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='summary',
        ),
        migrations.AddField(
            model_name='cart',
            name='name2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='song',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='title',
            field=models.TextField(),
        ),
    ]
