# Generated by Django 3.2 on 2021-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210514_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
