# Generated by Django 3.2 on 2021-05-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20210514_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name2',
            field=models.TextField(blank=True, default='Anonymous', null=True),
        ),
    ]
